const api=require('../../services/orders'),cart=require('../../utils/cart'),fmt=require('../../utils/format'),layout=require('../../utils/layout')
Page({
  data:{topInset:layout.topInset(),tab:'history',orders:[],activeCount:0,searchOpen:false,keyword:'',loading:true,error:''},
  onShow(){const requested=wx.getStorageSync('orders_open_tab');if(requested){wx.removeStorageSync('orders_open_tab');this.setData({tab:requested})}this.load()},
  choose(e){this.setData({tab:e.currentTarget.dataset.tab});this.load()},
  async load(){this.setData({loading:true,error:''});try{await getApp().loginPromise;const [list,active]=await Promise.all([api.list(this.data.tab),this.data.tab==='history'?api.list('active'):Promise.resolve([])]);list.forEach(o=>{o.mealLabel=fmt.meal[o.mealType];o.dateLabel=fmt.date(o.mealDate);o.displayImage=o.servedImageUrl||(o.items[0]&&o.items[0].dishImageUrl)||'';o.reviewText=(o.reviews||[]).find(review=>review.comment)?.comment||''});this._allOrders=list;this.setData({orders:list,activeCount:this.data.tab==='history'?active.length:list.length,loading:false},()=>this.applySearch());if(this.data.tab==='active'){const {request}=require('../../services/api');request({url:'/api/notifications/read',method:'PUT'}).then(()=>wx.removeTabBarBadge({index:2})).catch(()=>{})}}catch(e){this.setData({error:e.message,loading:false})}},
  toggleSearch(){this.setData({searchOpen:!this.data.searchOpen,keyword:!this.data.searchOpen?this.data.keyword:''},()=>this.applySearch())},
  input(e){this.setData({keyword:e.detail.value},()=>this.applySearch())},
  clearSearch(){this.setData({keyword:''},()=>this.applySearch())},
  applySearch(){const needle=String(this.data.keyword||'').trim().toLowerCase();this.setData({orders:needle?(this._allOrders||[]).filter(order=>[order.mealLabel,order.message,order.creatorName,...order.items.map(i=>i.dishName)].join(' ').toLowerCase().includes(needle)):(this._allOrders||[])})},
  showActions(e){const id=e.currentTarget.dataset.id;wx.showActionSheet({itemList:['再来一顿','删除记录'],success:result=>{const event={currentTarget:{dataset:{id}}};if(result.tapIndex===0)this.reorder(event);else this.remove(event)}})},
  detail(e){wx.navigateTo({url:`/pages/order-detail/order-detail?id=${e.currentTarget.dataset.id}`})},
  async reorder(e){try{const data=await api.reorder(e.currentTarget.dataset.id);data.items.forEach(i=>{if(i.dishId)cart.add({id:i.dishId,name:i.dishName,imageUrl:i.imageUrl,calorieKcal:i.calorieKcal,calorieUnit:i.calorieUnit},i.quantity)});wx.showToast({title:'已经放回小菜单啦',icon:'none'});wx.navigateTo({url:'/pages/cart/cart'})}catch(err){wx.showToast({title:err.message,icon:'none'})}},
  async remove(e){const result=await new Promise(resolve=>wx.showModal({title:'删除这条饭饭记录？',content:'菜品和这顿饭的信息会一起删除，无法恢复。',confirmText:'删除',confirmColor:'#C45F7D',success:resolve}));if(!result.confirm)return;try{await api.remove(e.currentTarget.dataset.id);wx.showToast({title:'记录已删除',icon:'none'});this.load()}catch(err){wx.showToast({title:err.message,icon:'none'})}}
})
