const api=require('../../services/orders'),cart=require('../../utils/cart'),fmt=require('../../utils/format'),upload=require('../../services/upload')
Page({
  data:{id:null,order:null,loading:true,error:'',serving:false},
  onLoad(q){this.setData({id:q.id});this.load()},
  async load(){try{const o=await api.detail(this.data.id);o.mealLabel=fmt.meal[o.mealType];o.dateLabel=fmt.date(o.mealDate);o.isServable=['pending','accepted','preparing'].includes(o.status);this.setData({order:o,loading:false,error:''})}catch(e){this.setData({error:e.message,loading:false})}},
  async serve(){try{const choice=await new Promise((resolve,reject)=>wx.showActionSheet({itemList:['上传一张上菜照片','直接标记上菜'],success:resolve,fail:reject}));let image={};if(choice.tapIndex===0){const media=await new Promise((resolve,reject)=>wx.chooseMedia({count:1,mediaType:['image'],sourceType:['album','camera'],success:resolve,fail:reject}));this.setData({serving:true});image=await upload.uploadImage(media.tempFiles[0].tempFilePath,'meal')}await api.serve(this.data.id,image);wx.showToast({title:'上菜成功，准备开饭啦 ❤️',icon:'none'});this.load()}catch(e){if(!String(e.errMsg||'').includes('cancel'))wx.showToast({title:e.message||'上菜失败',icon:'none'})}finally{this.setData({serving:false})}},
  async finish(){try{await api.status(this.data.id,'completed');wx.showToast({title:'吃完啦 ❤️',icon:'none'});this.load()}catch(e){wx.showToast({title:e.message,icon:'none'})}},
  async cancel(){const r=await new Promise(resolve=>wx.showModal({title:'取消这次点菜？',content:'记录会保留，但不会再继续准备。',success:resolve}));if(r.confirm){try{await api.status(this.data.id,'cancelled');this.load()}catch(e){wx.showToast({title:e.message,icon:'none'})}}},
  async remove(){const r=await new Promise(resolve=>wx.showModal({title:'删除这条饭饭记录？',content:'删除后无法恢复。',confirmText:'删除',confirmColor:'#C45F7D',success:resolve}));if(!r.confirm)return;try{await api.remove(this.data.id);wx.showToast({title:'记录已删除',icon:'none'});setTimeout(()=>wx.navigateBack(),350)}catch(e){wx.showToast({title:e.message,icon:'none'})}},
  async reorder(){try{const data=await api.reorder(this.data.id);data.items.forEach(i=>i.dishId&&cart.add({id:i.dishId,name:i.dishName,imageUrl:i.imageUrl,calorieKcal:i.calorieKcal,calorieUnit:i.calorieUnit},i.quantity));wx.navigateTo({url:'/pages/cart/cart'})}catch(e){wx.showToast({title:e.message,icon:'none'})}}
})
