const api=require('../../services/orders'),cart=require('../../utils/cart'),fmt=require('../../utils/format'),upload=require('../../services/upload')
Page({
  data:{id:null,order:null,loading:true,error:'',serving:false,comment:'',currentUserId:null},
  onLoad(q){this.setData({id:q.id,currentUserId:(wx.getStorageSync('user')||{}).id||null});this.load()},
  async load(clearDraft=true){try{const o=await api.detail(this.data.id);o.mealLabel=fmt.meal[o.mealType];o.dateLabel=fmt.date(o.mealDate);o.isServable=['pending','accepted','preparing'].includes(o.status);o.isRecorded=['ready','completed'].includes(o.status);o.comments=(o.reviews||[]).filter(item=>item.comment).map(item=>({...item,createdLabel:fmt.dateTime(item.createdAt),isMine:Number(item.userId)===Number(this.data.currentUserId)}));this.setData({order:o,comment:clearDraft?'':this.data.comment,loading:false,error:''})}catch(e){this.setData({error:e.message,loading:false})}},
  async serve(){try{const choice=await new Promise((resolve,reject)=>wx.showActionSheet({itemList:['上传一张上菜照片','直接标记已上菜'],success:resolve,fail:reject}));let image={};if(choice.tapIndex===0){const media=await new Promise((resolve,reject)=>wx.chooseMedia({count:1,mediaType:['image'],sourceType:['album','camera'],success:resolve,fail:reject}));this.setData({serving:true});image=await upload.uploadImage(media.tempFiles[0].tempFilePath,'meal')}await api.serve(this.data.id,image);wx.showToast({title:'上菜成功啦',icon:'success',duration:1500});wx.setStorageSync('orders_open_tab','history');setTimeout(()=>wx.switchTab({url:'/pages/orders/orders'}),850)}catch(e){if(!String(e.errMsg||'').includes('cancel'))wx.showToast({title:e.message||'上菜失败',icon:'none'})}finally{this.setData({serving:false})}},
  comment(e){this.setData({comment:e.detail.value})},
  async saveComment(){const comment=this.data.comment.trim();if(!comment){wx.showToast({title:'先写一句感受吧',icon:'none'});return}try{await api.review(this.data.id,{comment});this.setData({comment:''});wx.showToast({title:'评论保存好啦',icon:'success',duration:1400});this.load()}catch(e){wx.showToast({title:e.message,icon:'none'})}},
  async deleteComment(){const result=await new Promise(resolve=>wx.showModal({title:'删除这条评论？',content:'删除后不能恢复，照片不会受影响。',confirmText:'删除',confirmColor:'#C45F7D',success:resolve}));if(!result.confirm)return;try{await api.removeReview(this.data.id);wx.showToast({title:'评论已删除',icon:'none'});this.load()}catch(e){wx.showToast({title:e.message,icon:'none'})}},
  async addPhoto(){try{const media=await new Promise((resolve,reject)=>wx.chooseMedia({count:1,mediaType:['image'],sourceType:['album','camera'],success:resolve,fail:reject}));const image=await upload.uploadImage(media.tempFiles[0].tempFilePath,'meal');await api.review(this.data.id,image);wx.showToast({title:'照片保存好啦',icon:'success',duration:1400});this.load(false)}catch(e){if(!String(e.errMsg||'').includes('cancel'))wx.showToast({title:e.message||'照片上传失败',icon:'none'})}},
  async cancel(){const r=await new Promise(resolve=>wx.showModal({title:'取消这次点菜？',content:'记录会保留，但不会再等待上菜。',success:resolve}));if(r.confirm){try{await api.status(this.data.id,'cancelled');wx.showToast({title:'已取消',icon:'none'});this.load()}catch(e){wx.showToast({title:e.message,icon:'none'})}}},
  async remove(){const r=await new Promise(resolve=>wx.showModal({title:'删除这条饭饭记录？',content:'删除后无法恢复。',confirmText:'删除',confirmColor:'#C45F7D',success:resolve}));if(!r.confirm)return;try{await api.remove(this.data.id);wx.showToast({title:'记录已删除',icon:'none'});setTimeout(()=>wx.navigateBack(),350)}catch(e){wx.showToast({title:e.message,icon:'none'})}},
  async reorder(){try{const data=await api.reorder(this.data.id);data.items.forEach(i=>i.dishId&&cart.add({id:i.dishId,name:i.dishName,imageUrl:i.imageUrl,calorieKcal:i.calorieKcal,calorieUnit:i.calorieUnit},i.quantity));wx.navigateTo({url:'/pages/cart/cart'})}catch(e){wx.showToast({title:e.message,icon:'none'})}}
})
