const {request}=require('./api')
const MAX_ORIGINAL_BYTES=10*1024*1024
const TARGET_UPLOAD_BYTES=2*1024*1024
function info(path){return new Promise((resolve,reject)=>wx.getFileInfo({filePath:path,success:resolve,fail:reject}))}
function read(path){return new Promise((resolve,reject)=>wx.getFileSystemManager().readFile({filePath:path,success:r=>resolve(r.data),fail:reject}))}
function compress(path,quality){return new Promise((resolve,reject)=>wx.compressImage({src:path,quality,success:r=>resolve(r.tempFilePath),fail:reject}))}
function hmacSha1(key,message){try{return Promise.resolve(require('../utils/crypto-lite').hmacSha1(message,key))}catch(_){return Promise.reject(new Error('本地 COS 签名组件加载失败，请重新编译小程序'))}}
// COS V5 requires the request Host to be in the canonical signed headers.
async function buildAuthorization(data,method,path,host){const start=Math.floor(Date.now()/1000)-1,end=data.expiredTime,keyTime=`${start};${end}`,signKey=await hmacSha1(data.credentials.tmpSecretKey,keyTime),httpString=`${method.toLowerCase()}\n${path}\n\nhost=${host}\n`,sha1=require('../utils/crypto-lite').sha1(httpString),stringToSign=`sha1\n${keyTime}\n${sha1}\n`,signature=await hmacSha1(signKey,stringToSign);return `q-sign-algorithm=sha1&q-ak=${data.credentials.tmpSecretId}&q-sign-time=${keyTime}&q-key-time=${keyTime}&q-header-list=host&q-url-param-list=&q-signature=${signature}`}
async function uploadImage(path,purpose='dish',onStage){const ext=(path.split('.').pop()||'jpg').toLowerCase(),mimeType=ext==='png'?'image/png':ext==='webp'?'image/webp':'image/jpeg';let original,file,uploadPath=path,data;try{original=await info(path)}catch(_){throw new Error('读取图片失败，请重新选择一张')}if(original.size>MAX_ORIGINAL_BYTES)throw new Error('原图超过 10MB，请先裁剪或选择更小的图片');try{onStage?.('compressing');uploadPath=await compress(path,80);file=await info(uploadPath);if(file.size>TARGET_UPLOAD_BYTES){uploadPath=await compress(path,60);file=await info(uploadPath)}}catch(e){console.warn('[image compression] failed',{errMsg:e.errMsg||String(e)});file=original;uploadPath=path}if(file.size>TARGET_UPLOAD_BYTES)throw new Error('图片压缩后仍超过 2MB，请裁剪后再试');try{onStage?.('credential');data=await request({url:'/api/uploads/cos-credential',method:'POST',data:{mimeType,size:file.size,purpose}})}catch(e){throw new Error(`获取上传凭证失败：${e.message||'请检查后端服务'}`)}const host=`${data.bucket}.cos.${data.region}.myqcloud.com`;let authorization,body;try{onStage?.('uploading');authorization=await buildAuthorization(data,'PUT',`/${data.key}`,host);body=await read(uploadPath)}catch(e){throw new Error(`准备图片失败：${e.message||'请重新选择图片'}`)}return new Promise((resolve,reject)=>wx.request({url:`https://${host}/${data.key}`,method:'PUT',data:body,timeout:15000,header:{Authorization:authorization,'x-cos-security-token':data.credentials.sessionToken,'Content-Type':mimeType},success:r=>{if(r.statusCode>=200&&r.statusCode<300)return resolve({imageKey:data.key,imageUrl:data.url,originalSize:original.size,uploadSize:file.size});console.warn('[COS upload] rejected',{statusCode:r.statusCode,requestId:r.header?.['x-cos-request-id']||''});reject(new Error(`图片上传失败（COS ${r.statusCode}）`))},fail:e=>{console.warn('[COS upload] network failure',{errMsg:e.errMsg||''});reject(new Error(`图片上传网络失败：${e.errMsg||'请检查网络或 COS 域名设置'}`))}}))}
module.exports={uploadImage}
