const {request}=require('./api')
function info(path){return new Promise((resolve,reject)=>wx.getFileInfo({filePath:path,success:resolve,fail:reject}))}
function read(path){return new Promise((resolve,reject)=>wx.getFileSystemManager().readFile({filePath:path,success:r=>resolve(r.data),fail:reject}))}
async function uploadImage(path,purpose='dish'){const ext=(path.split('.').pop()||'jpg').toLowerCase(),mimeType=ext==='png'?'image/png':ext==='webp'?'image/webp':'image/jpeg',file=await info(path),data=await request({url:'/api/uploads/cos-credential',method:'POST',data:{mimeType,size:file.size,purpose}}),host=`https://${data.bucket}.cos.${data.region}.myqcloud.com`,authorization=await buildAuthorization(data,'put',`/${data.key}`),body=await read(path);return new Promise((resolve,reject)=>wx.request({url:`${host}/${data.key}`,method:'PUT',data:body,header:{Authorization:authorization,'x-cos-security-token':data.credentials.sessionToken,'Content-Type':mimeType},success:r=>r.statusCode<300?resolve({imageKey:data.key,imageUrl:data.url}):reject(new Error('图片上传失败')),fail:reject}))}
// COS V5 signing is delegated to the official temporary secret. wx upload needs an Authorization header;
// this implementation uses wx.getFileSystemManager only for the file body and signs canonical empty headers.
function hmacSha1(key,message){return new Promise((resolve,reject)=>{try{const CryptoJS=require('../utils/crypto-lite');resolve(CryptoJS.hmacSha1(message,key))}catch(_){reject(new Error('缺少 COS 签名模块，请按部署文档安装 cos-wx-sdk-v5'))}})}
async function buildAuthorization(data,method,path){const start=Math.floor(Date.now()/1000)-1,end=data.expiredTime,keyTime=`${start};${end}`,signKey=await hmacSha1(keyTime,data.credentials.tmpSecretKey),httpString=`${method}\n${path}\n\n\n`,sha1=require('../utils/crypto-lite').sha1(httpString),stringToSign=`sha1\n${keyTime}\n${sha1}\n`,signature=await hmacSha1(stringToSign,signKey);return `q-sign-algorithm=sha1&q-ak=${data.credentials.tmpSecretId}&q-sign-time=${keyTime}&q-key-time=${keyTime}&q-header-list=&q-url-param-list=&q-signature=${signature}`}
module.exports={uploadImage}
